//! #1, #2, #4 — file-driven CoW known-answer tests.
//!
//! `fixtures/cow/vectors.json` was generated by an INDEPENDENT oracle (the committed
//! `gen.ts` via ethers v6) — each vector pins an `expected_digest` (the GPv2 EIP-712 signing
//! hash) and an `expected_uid` (the 56-byte order uid) for a fully-specified order. This test
//! rebuilds each order as a `deckard_contract::SwapOrder` and asserts our pure
//! `deckard_core::order_digest` / `order_uid` reproduce the oracle's bytes exactly. A drift in
//! the domain, the type hash, the field layout, or the uid concatenation fails here.
//!
//! It also re-asserts the canonical app-data hash and the `apply_slippage` table at the
//! integration level (both are unit-tested in core too — this is the cross-crate belt-and-braces).

use std::path::PathBuf;
use std::str::FromStr;

use alloy_primitives::{hex, Address, B256, U256};
use deckard_contract::SwapOrder;
use deckard_core::{apply_slippage, order_digest, order_uid, APP_DATA_HASH};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct VectorFile {
    vectors: Vec<Vector>,
}

#[derive(Debug, Deserialize)]
struct Vector {
    name: String,
    chain_id: u64,
    owner: String,
    order: OrderFields,
    expected_digest: String,
    expected_uid: String,
}

#[derive(Debug, Deserialize)]
struct OrderFields {
    sell_token: String,
    buy_token: String,
    receiver: String,
    /// decimal string (wei) — NOT 0x-hex.
    sell_amount: String,
    /// decimal string (wei) — NOT 0x-hex.
    buy_amount_min: String,
    valid_to: u32,
    /// 0x-hex 32-byte appData hash.
    app_data: String,
}

/// `0x…` (or bare) hex → `Address`. Panics on malformed input (test code is lint-exempt).
fn addr(s: &str) -> Address {
    Address::from_str(s).expect("vector address")
}

/// `0x…` hex → `B256`. Panics on malformed input.
fn b256(s: &str) -> B256 {
    B256::from_str(s).expect("vector b256")
}

/// decimal string → `U256`. The CoW wire (and these fixtures) carry token amounts as decimal
/// strings, so parse base-10 (NOT the `0x`-hex `from_str`).
fn dec(s: &str) -> U256 {
    U256::from_str_radix(s, 10).expect("vector decimal amount")
}

fn load_vectors() -> Vec<Vector> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("cow")
        .join("vectors.json");
    let raw =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let parsed: VectorFile = serde_json::from_str(&raw).expect("parse vectors.json");
    parsed.vectors
}

/// Lowercase, 0x-stripped hex of a byte slice, for stable comparison against the fixture's
/// `expected_uid` / `expected_digest` strings.
fn hex_no_prefix(bytes: &[u8]) -> String {
    hex::encode(bytes)
}

fn strip0x(s: &str) -> &str {
    s.strip_prefix("0x").unwrap_or(s)
}

#[test]
fn cow_digest_and_uid_match_oracle_vectors() {
    let vectors = load_vectors();
    assert!(
        vectors.len() >= 3,
        "expected at least 3 oracle vectors, got {}",
        vectors.len()
    );

    for v in &vectors {
        let owner = addr(&v.owner);
        let order = SwapOrder {
            chain_id: v.chain_id,
            owner,
            sell_token: addr(&v.order.sell_token),
            buy_token: addr(&v.order.buy_token),
            sell_amount: dec(&v.order.sell_amount),
            buy_amount_min: dec(&v.order.buy_amount_min),
            receiver: addr(&v.order.receiver),
            valid_to: v.order.valid_to,
            app_data: b256(&v.order.app_data),
        };

        // (#1) EIP-712 signing digest must equal the oracle's.
        let digest = order_digest(&order);
        let expected_digest = b256(&v.expected_digest);
        assert_eq!(
            digest, expected_digest,
            "digest mismatch for vector '{}'",
            v.name
        );

        // (#2) 56-byte order uid = digest(32) || owner(20) || validTo(4 BE).
        let uid = order_uid(digest, owner, order.valid_to);
        let got_uid_hex = hex_no_prefix(&uid);
        let want_uid_hex = strip0x(&v.expected_uid).to_lowercase();
        assert_eq!(
            got_uid_hex, want_uid_hex,
            "uid mismatch for vector '{}'",
            v.name
        );
        // The uid embeds the digest verbatim in its first 32 bytes.
        let (uid_digest, _rest) = uid.split_at(32);
        assert_eq!(
            uid_digest,
            digest.as_slice(),
            "uid first 32 bytes must be the digest (vector '{}')",
            v.name
        );
    }
}

#[test]
fn app_data_hash_matches_canonical_doc() {
    // keccak256("{}") — the canonical empty app-data doc — must equal the re-exported const.
    // Every vector's app_data field is exactly this hash, so assert that too.
    let expected = b256("0xb48d38f93eaa084033fc5970bf96e559c33c4cdc07d889ab00b4d63f9590739d");
    assert_eq!(APP_DATA_HASH, expected, "APP_DATA_HASH drifted");

    for v in load_vectors() {
        assert_eq!(
            b256(&v.order.app_data),
            APP_DATA_HASH,
            "vector '{}' carries a non-canonical app_data",
            v.name
        );
    }
}

#[test]
fn slippage_table_at_integration_level() {
    // 0 bps → identity (no deduction).
    let amount = U256::from(2_000_000_000_000_000_000u64); // 2e18
    assert_eq!(apply_slippage(amount, 0), amount, "0 bps must be identity");

    // 10000 bps (100%) → floor to zero.
    assert_eq!(
        apply_slippage(amount, 10_000),
        U256::ZERO,
        "10000 bps must zero the amount"
    );

    // 50 bps (0.50%) of 2e18 = 1e16 → min 1.99e18 (the default-slippage floor).
    assert_eq!(
        apply_slippage(amount, 50),
        U256::from(1_990_000_000_000_000_000u64),
        "50 bps of 2e18 should leave 1.99e18"
    );

    // Tiny-amount rounding: the deduction rounds UP (conservative — never accept LESS than the
    // floor allows). 1 bps of 1 atom = 0.0001, ceil → 1, so min = 0.
    assert_eq!(
        apply_slippage(U256::from(1u64), 1),
        U256::ZERO,
        "rounding-up deduction on a 1-atom amount must floor to 0"
    );

    // A slightly larger tiny case: 1 bps of 10000 atoms = 1.0 exactly → deduction 1 → 9999.
    assert_eq!(
        apply_slippage(U256::from(10_000u64), 1),
        U256::from(9_999u64),
        "1 bps of 10000 atoms leaves 9999"
    );

    // bps beyond 100% saturates to zero, never underflows.
    assert_eq!(
        apply_slippage(amount, u16::MAX),
        U256::ZERO,
        "over-100% bps saturates to zero"
    );
}
